blank_issues_enabled: false
contact_links:
  - name: Community Forum
    url: https://anonupload.us/discuss
    about: Ask a question, get answers. Anything not related to a feature request OR bug report should go here.
