name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Package Registry
      uses: craftech-io/package-action@v3.1.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
        username: supernova3339
        image_name: anonupload
