name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --name anonupload -p 80:80 -v /etc/anonupload/files:/var/www/html/files -e ADMIN_EMAIL=admin@admin.com -e ADMIN_PASSWORD=password -e APP_FILELIST=jpeg,jpg,gif,png,zip,xls,doc,mp3,mp4,mpeg,wav,avi,rar,7z,txt -e APP_SIZE_VERIFICATION=true -e APP_FILE_DESTINATION=files -e APP_BASE_URL=https://xxx.xxx/ -e APP_MAX_SIZE=10000000000 -e APP_MIN_SIZE=0 -e APP_CONTACT_EMAIL=changeme@dontforget.okay -e APP_DOWNLOAD_TIME=30 ghcr.io/supernova3339/anonfiles:1
