name: Move new issues into Todo

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Anonupload Roadmap
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
